# Generated by Django 2.2.4 on 2019-08-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20190821_0928'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Myprofile',
        ),
    ]
