# Generated by Django 2.2.4 on 2019-08-20 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleposts',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
