# Generated by Django 2.2.4 on 2019-08-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190820_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleposts',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
