# Generated by Django 2.2.4 on 2019-08-22 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190822_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleposts',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='blog.ArticleColumn'),
        ),
    ]
